### ISSUE TITLE
[Namespaces] Ajout d'un onglet "Notes" récapitulant l'ensemble des additional notes d'un espace de noms [1039]

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#10]
**Cas d'utilisation**

L'application permet de créer, dans une version *ongoing* d'un espace de noms A, des _additional notes_ (notes complémentaires) sur des classes ou propriétés d'un espace de noms B, ongoing ou fermé (voir #1027).

Actuellement il n'est pas possible de retrouver ces notes à moins de se rendre sur une des entités liées, il faut donc ajouter un moyen de les retrouver facilement.

**Implémentation**

Dans la fiche d'un espace de noms :

* Ajouter un onglet "Notes" à droite de "Relations"

**Contenu de l'onglet "Notes"**

* Ajouter un tableau récapitulant les notes appartenant à l'espace de noms, à la manière du tableau des relations d'un espace noms et de celui des notes d'une entité avec les colonnes suivantes :

* *Show* : un œil avec un popup pour faire apparaître l'intégralité de la note.
* *Note* : le texte de la note (affichage uniquement des premiers caractères comme dans les tableaux des notes d'une entité).
* *Type* : type de l'additional note.
* *Language* : le code de la langue.
* *Entity* : préfixe ns + id + label de l'entité (classe ou propriété).

* Seule la colonne Entity est cliquable et renvoie vers la fiche de l'entité (onglet Definition de l'entité source).

* Au dessus du tableau, ajouter des boutons de filtre rapide (Filter by) :
** Internal notes / Context notes / Bibliographical notes / All
* Par défaut la sélection est à "All".

**Comment by valamercery** [comment]
Très bien mais il manque le filtre rapide.

**Comment by perrauda** [comment]
Un select a été rajouté sur la colonne type pour filtrer les notes

**Comment by perrauda** [comment]
Ticket mis en production
merge nécessaire @dferhod

**Comment by dferhod** [comment]
Review OK
Juste un commentaire pour le CSS :
https://git.msh-lse.fr/larhra/ontome/-/merge_requests/88#note_2071

**Comment by perrauda** [comment]
C'est fait
