### ISSUE TITLE
[Summary] Ajouter les cardinalités [1046]

### ISSUE THREAD

**Issue by valamercery** [geovistory/ontome#107]
**Problem description / use case**

**Functional Requirements**
Rajouter la cardinalité en fin de ligne des propriétés dans le summary d'une classe.

ex : sdh-int:C9 Asserted Actor's Role → sdh-int:P18 is qualified by (qualifies) (0,n:0,1)

**Technical Specification**
A clear and concise description of how the feature is implemented.

**Acceptance criteria**
What has the reviewer to test?

**Comment by valamercery** [comment]
Vérifier l'état d'avancement.

**Comment by perrauda** [comment]
La branche existe - à relier

**Comment by joschne** [comment]
> La branche existe - à relier

@perrauda does a PR exist? if so, please create the link and add the issue to OM-merge-prs.

**Comment by perrauda** [comment]
> > La branche existe - à relier
> 
> @perrauda does a PR exist? if so, please create the link and add the issue to OM-merge-prs.

Done
