### ISSUE TITLE
[URGENT] Can't create class/property

### ISSUE THREAD

**Issue by valamercery** [geovistory/ontome#114]
**Describe the bug**  
Impossible de créer une classe/propriété dans un espace de noms avec URI interne, cf. screen.

![](https://github.com/geovistory/ontome/assets/51914812/a3aa1182-9510-40c8-8326-f4bfd8f81503)

**To Reproduce**  

1.  Go to your namespace, classes tab
2.  Click on create
3.  Fill the form
4.  Click save
5.  See error

**Expected behavior**  
Pouvoir créer une classe :-)

**Comment by stephenhart8** [comment]
Maybe linked to this issue, the Collecte profile that contains the new classes created directly in the database by Vincent and me seems to create some problems in the Geovistory Toolbox.
In the project Default Configuration Project (375669), in the Settings > Classes, if the Collect profile is activated, no classes appear. But if the Collect profile is deactivated, all the classes are visible again.

https://cdn.discordapp.com/attachments/1088817458334404749/1178683931571269764/image.png?ex=657709f4&is=656494f4&hm=73ded3e308dd3e1800811bc26a6f8a1ff77b691bbf1829e6b0aaee2b001255da&
