### ISSUE TITLE
Display bug of the class hierarchy

### ISSUE THREAD

**Issue by stephenhart8** [geovistory/ontome#117]
**Describe the bug**
In the hierarchy view of the classes, some entities are not lined up properly, and also not expandable 

**To Reproduce**
1. Go to 'Class Tree'
2. Click on 'E1>E77>E70>E71'

Here is a screenshot of how it is displayed on my computer:

<img width="742" alt="Capture d’écran 2023-11-28 à 16 47 37" src="https://github.com/geovistory/ontome/assets/49342191/04094aa7-0650-4c33-83e4-735cedcd51f7">

When I click on E24, nothing is expanded (or rather, I don't see what is expanded)

**Comment by dferhod** [comment]
Can you provide your web browser name and its version number please?

**Comment by stephenhart8** [comment]
Chrome Version 119.0.6045.159 (Build officiel) (x86_64)

<img width="748" alt="Capture d’écran 2023-11-28 à 17 30 12" src="https://github.com/geovistory/ontome/assets/49342191/3e533a9b-1075-48df-98a7-37063e2da488">

**Comment by dferhod** [comment]
Ok thank you.
I have the exact same version, but can't reproduce the bug.
Can you tell us your screen resolution please?

**Comment by stephenhart8** [comment]
Here are my computer specs:

<img width="555" alt="Capture d’écran 2023-11-29 à 09 51 03" src="https://github.com/geovistory/ontome/assets/49342191/0fab20f3-8933-42d1-9f3f-342428800383">

**Comment by stephenhart8** [comment]
The display bug is still present, but at least things are clickable this morning:

<img width="1179" alt="Capture d’écran 2023-11-29 à 09 53 25" src="https://github.com/geovistory/ontome/assets/49342191/6e4ebf60-0c9c-4ece-9661-420982bd63df">

**Comment by perrauda** [comment]
Can you share with us how your dashboard is set up (which namespaces are activated, etc.)?

**Comment by stephenhart8** [comment]
It's the SDHSS master that is activated.
<img width="1296" alt="Capture d’écran 2023-11-29 à 10 21 12" src="https://github.com/geovistory/ontome/assets/49342191/a1d299f2-aaf8-435c-ae87-49281f1a7ec4">

Maybe we could also have a quick video call so I can share my screen and we can try and see what could be the issue? But if it's only visible on my computer, maybe it's not that big of a deal?

**Comment by perrauda** [comment]
I wanted to see the "My current namespaces" tab. I was able to look at your configuration in the database
I noticed some possible inconsistencies in the selection (for example, CIDOC CRM 7 is selected and is incompatible with SDHSS, I think). I recommend resetting all the namespaces selected with the green button ("Reset") and let me know if that solves the problem or not.

**Comment by valamercery** [comment]
The issue is caused by the selection of two versions of the same namespace in the dashboard. This works for the classes list but not for the classes tree, which can only display one version at a time.  This isn't really a bug, but a malfunction. A new issue will be created to add a feature that will warn the user that he cannot display two different versions of the same namespace in the classes tree.
