### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by rnsrk** [geovistory/ontome#129]
**Describe the bug**
New set passwords with the "Request new password" do not work.

**To Reproduce**
I forgot my password for account "[deleted]", so I visit https://ontome.net/login, 
click [Request new password](https://ontome.net/request-password)
I type my email.
I get a Email.
I set a new password.
I can't login with the new password.

**Expected behavior**
The new Password should work.

**Comment by perrauda** [comment]
Hello,

After checking, changing my password and using the new one does not cause me any problems.

However, it seems that you currently have two accounts: rnsrk and rbrtnsrk.

Try with rbrtnsrk?

Best regards

**Comment by rnsrk** [comment]
I remember only one account, and the email is maybe not accessible (its long time ago), and I try to request a new password to an email with a account I forgot. But you can just delete both accounts connected with my name and I will re-register with current infos. Thank you!

**Comment by valamercery** [comment]
Hi, I'lll take care of the problem and contact you by e-mail.
