### ISSUE TITLE
[Namespaces et profils] Les espaces de noms et profils ongoing ne doivent plus être visibles en dehors du projet [975]

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#14]
### Cas d'utilisation

Certains utilisateurs souhaiteraient pouvoir "cacher" leur travail en ongoing durant le temps de la réalisation que cela soit pour les espaces de noms ou les profils, ceci avant de publier une version visible à tous.
D'autres en revanche souhaitent au contraire rendre visible leur travail.

### Règle générale

* Faire en sorte que, par défaut, les classes et propriétés des espaces de noms et profils ongoing ne soient visibles QUE par les membres du projet d'appartenance.
* Ajouter une fontionnalité permettant de rendre visible les classes et propriétés d'un espace de noms/profil ongoing.
* Le fait de rendre visible les classes et propriétés d'un ongoing est irreversible.

### Onglet "Identification"

* Ajouter dans les onglets "identification" d'un espace de noms et d'un profil une coche permettant de rendre visible à tous les classes et propriétés d'une version *ongoing*, à la manière du bouton permettant de forcer la publication d'un profil ongoing dans l'API :
  * Nommer cette coche "Make the classes and properties of this namespace/profile visible". Seul l'administrateur du projet peut -cocher/décocher cette case.- faire cette action.
  * Pour un espace de noms, ajouter ce message : "Once the classes and properties of an ongoing namespace are made visible, it's not possible to hide them again or to create new ones that would be hidden. Do you wish to proceed?"
  * Pour un profil, ajouter ce message : "Once the classes and properties of an ongoing profile are made visible, it's not possible to hide them again or to add new ones that would be hidden. Do you wish to proceed?" 
* Le fait de forcer la publication d'un profil dans l'API le rend automatiquement visible.
  * Pour les profils ongoing *cachés* uniquement, changer le texte d'avertissement qui s'affiche au moment de forcer la publication d'un profil ongoing ("allow API connection") en "It's not advisable to allow an API connection on an ongoing profile. This will also make the content of this profile visible to everyone. Do you wish to proceed?"
  * En profiter pour changer la phrase pour les profils ongoing *visibles* en "It's not advisable to allow an API connection on an ongoing profile. Do you wish to proceed?"

### Onglets "Classes" et "Properties"

* Dans les onglets "Classes" et "Properties" d'un espace de noms/profil ongoing non visible, remplacer le tableau par la phrase : "The classes/properties in this ongoing namespace/profile are currently only visible to members of the [nom du projet cliquable] project.".

### Onglet "Graph"

* Dans les onglets "Graph" d'un espace de noms/profil ongoing non visible, remplacer le graph par la phrase : "This graph of an ongoing namespace/profil is currently only visible to members of the [nom du projet cliquable] project.".

### Onglet "Profiles" d'une classe/propriété

* Ne pas afficher les profils non visibles dans le tableau "Profiles using this class/property"

### Tableau de bord

* Un espace de noms ongoing dont les classes et propriétés sont cachées ne doit pas être sélectionnable dans "my current namespace" pour un utilisateur non membre du projet de l'espace de noms.

### Lien direct vers une classe/propriété

* En cas de lien direct vers une classe ou une propriété appartenant à un espace de noms ongoing les cachant, remplacer toute la fiche par la phrase "This class/property belongs to an ongoing namespace that is only visible to members of the [nom du projet cliquable] project.".

### Ticket lié

* #15

**Comment by perrauda** [comment]
@valamercery 
Testable sur http://phn-dev.ish-lyon.cnrs.fr/ontologies/web/

**Comment by valamercery** [comment]
- En testant, je me rends compte que nous avons oublié l'arborescence et la liste des classes/propriétés. Il faut exclure ici aussi l'affichage des classes/propriétés appartenant à un espace de noms ongoing caché. Ne pas oublier de les exclure aussi de la liste affichée avec "Show all namespaces".
- J'ajouterai bien la même fonctionnalité dans l'onglet "Namespaces" d'un profil ongoing caché avec la phrase "The selected namespaces in this ongoing profile are currently only visible to members of the [Nom du projet] project."
- Un détail, j'ajouterai "to everyone" après "visible" dans chaque phrase, sauf quand "visible" est suivi de "to members".
- Je referai un tour à la rentrée ;-) Dans tous les cas, il faudra qu'on fasse la mise en prod ensemble pour rendre visible tout de suite les espaces de noms ongoing de SDHSS.

**Comment by perrauda** [comment]
@valamercery 
J'ai apporté les modifications au niveau des 2 cases cochées ci-dessus

Pour la première case à cocher, j'ai mis à jour les listes des classes/propriétés mais pas le graphe car en y réfléchissant, le graphe est généré à partir du dashboard,or dans le dashboard il n'est pas possible de choisir les namespaces cachés n'est ce pas ?

Si je me trompe, peux tu me montrer une configuration dans lequel on voit des classes dans le graphe et qui sont normalement cachés.

Les changements sont effectifs en preprod

**Comment by valamercery** [comment]
Je suis d'accord pour l'arborescence, je testerai l'ensemble en preprod pour être sûrs.

**Comment by valamercery** [comment]
Pour mémoire, ajouter ici la liste des espaces de noms qui resteront visibles :

**Comment by valamercery** [comment]
Et vérifier si un espace de noms potentiellement prochainement caché n'est pas utilisé par l'un de ces ns :

3    "SDHSS Semantic Data for Humanities and Social Sciences CIDOC CRM Extension ongoing"  
28    "APIS - Austrian Bibliographic Lexicon Namespace v.0.1"  
30    "Geovistory (ongoing)"  
38    "READ-IT ongoing"  
66    "Maritime history ongoing"  
72    "CRM for Creative Processes Representation ongoing"  
74    "SDHSS Intellectual and Literary Life ongoing"  
80    "Alignment of symogih.org with CIDOC CRM ongoing"  
82    "HisArc-RDF ongoing"  
88    "Processetti ongoing"  
98    "Normative text (legislation) ongoing"  
110    "SDHSS CIDOC CRM supplement – ongoing"  
112    "SDHSS Social, legal and economic life ongoing"  
120    "CRM for Art and Architectural Argumentation ongoing"  
122    "CRMsoc ongoing"  
126    "Historique des unités administratives françaises ongoing"  
130    "Legal Provisions Ontology (LPO) ongoing"  
132    "Lumieres ongoing"  
138    "SDHSS Higher education and academies ongoing"  
140    "VOC Project namespace ongoing"  
144    "ATS"  
160    "SDHSS Social Life – Specific Aspects"  
164    "Forestry"  
178    "LabInVirtuo"  
184    "FFCC Andalucia ongoing"  
201    "SDHSS Voyage, movement, transport and displacement ongoing"  
205    "MoViEs"

**Comment by valamercery** [comment]
Après vérification, voici les espaces de noms à éventuellement corriger avant la mise en prod :
72
120
122
178

**Comment by perrauda** [comment]
- [ ] Réduire la liste de NS root dans le choix des références
