### ISSUE TITLE
OWL Export with more/alternate specifications

### ISSUE THREAD

**Issue by rnsrk** [geovistory/ontome#153]
**Problem description / use case**
OWL export misses hierarchical or constraint specifications:

### Major issues:
* Class hierarchy needs <rdfs:subClassOf> 
* Property hierarchy needs <rdfs:subPropertyOf>
* Inverse is not implemented for properties, i.e.  CIDOC-CRM describes "P1i_identifies" is inverse of "P1_is_identified_by", but this is not described in the OWL file, use <owl:inverseOf>
* Only object properties are used, but i. e. CIDOC-CRM use <owl:DatatypeProperty>  for  P3_has_note.

### Minor issues:
* Namespacing  xml:base namespace should be the main namespace not internal one (https://ontome.net/ns/xyz/)
* May add pref label in SKOS (<skos:prefLabel>) for concepts

**Comment by valamercery** [comment]
Thanks for your feedback, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/20

See also this other discussion: https://github.com/orgs/geovistory/discussions/16
