### ISSUE TITLE
OWL import

### ISSUE THREAD

**Issue by rnsrk** [geovistory/ontome#154]
**Problem description / use case**
I've got a bunch of existing OWL files and want to import it to OntoME. It takes a lot of time to remodel everything in OntoME.

**Functional Requirements**
Upload button for RDF/OWL, Turtle etc.

**Comment by valamercery** [comment]
Thanks for your feedback, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/19
