### ISSUE TITLE
Cannot add properties

### ISSUE THREAD

**Issue by rnsrk** [geovistory/ontome#155]
**Problem description / use case**
Property tab misses "Add" function.

**Functional Requirements**
Something similar to the classes tab:
![Bildschirmfoto vom 2024-03-01 08-14-05](https://github.com/geovistory/ontome/assets/29227376/74fa835f-ff21-4258-bd6e-78ab1a51c118)

**Comment by valamercery** [comment]
Hi @rnsrk please use [discussions](https://github.com/orgs/geovistory/discussions) to ask a question or provide feedback. Thanks!
