### ISSUE TITLE
Choix d'une licence open source

### ISSUE THREAD

**Issue by valamercery** [geovistory/ontome#18]
### Contexte

Dans le cadre du projet LOD4HSS et de la loi "Pour une République numérique" de 2016, le code d'OntoME devra être publié sous licence libre.

Licences permises pour les logiciels créés par l'administration française : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000034504991/

Complément, plaquette réseau DEVLOG CNRS "Je code : quels sont mes droits ? quelles sont mes obligations ?" : https://hal.science/hal-02399517

#### GNU GPLv3

La licence ouverte la plus utilisée.

:+1:  Licence très libre.
:-1: ~~probablement non totalement compatible avec le droit français, le droit moral étant "perpétuel, inaliénable et imprescriptible".~~ cf. article de loi

https://fr.wikipedia.org/wiki/Licence_publique_g%C3%A9n%C3%A9rale_GNU
https://www.gnu.org/licenses/gpl-3.0.fr.html
https://opensource.org/license/gpl-3-0/
https://choosealicense.com/licenses/gpl-3.0/

#### CeCiLL 2.1

Cette licence a été créée par le CNRS, le CEA et l'INRIA.

:+1: Licence ouverte compatible avec GNU GPLv3 et le droit français.
:-1: Licence peu utilisée et inconnue à l'international.

https://fr.wikipedia.org/wiki/Licence_CeCILL
https://cecill.info/licences/Licence_CeCILL_V2.1-fr.html
https://opensource.org/license/cecill-2-1/

#### EUPL 1.2

Cette licence a été créée et approuvée par la Commission européenne.

:+1: Licence ouverte compatible avec GNU GPLv3, CeCiLL 2.1 et le droit des pays membres.

https://fr.wikipedia.org/wiki/Licence_publique_de_l%27Union_europ%C3%A9enne
https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
https://opensource.org/license/eupl-1-2/

#### MIT

OntoME embarque du code sous licence MIT (Symfony, WebVOWL).

A priori, cette licence n'est pas contraignante et devrait être compatible avec les autres. 

https://fr.wikipedia.org/wiki/Licence_MIT
https://opensource.org/license/mit/
https://choosealicense.com/licenses/mit/

**Comment by joschne** [comment]
After discussion with @valamercery @dferhod @perrauda and @atterebf we decided to publish OntoME under the MIT License.
