### ISSUE TITLE
[namespaces] Les libellés des namespaces ongoing doivent conserver cette mention "ongoing"

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#20]
Contexte actuel: les utilisateurs peuvent retirer la mention "ongoing" dans les libellés des namespaces ongoing.

Normalement, il faudrait le remettre une fois qu'une version est publiée, mais après discussion sur Discord, on a décidé de modifier le comportement lors de l'édition du libellé.

A chaque fois qu'on édite le label, on propose de n'éditer que la partie éditable, c'est à dire sans le terme "ongoing" que l'on ne peut supprimer.

Exemple:

Au départ, on a: `CRMtest ongoing`
A l'édition, on ne peut éditer que la partie éditable, à savoir: `CRMtest`
L'utilisateur rajoute la version: `CRMtest v1.1` et valide.
Le nouveau libellé sera donc `CRMtest v1.1 ongoing`

A sa publication, le libellé sera bien `CRMtest v1.1` comme attendu [partie déjà implementée]

Le champ pour éditer le libellé sera accompagné de cette mention:
`The word "ongoing" is automatically added to the label of an ongoing version. It will be removed on publication.`

**Comment by valamercery** [comment]
Pour éviter toute confusion, supprimer la mention "ongoing" du label lors de la validation de la publication.

**Comment by perrauda** [comment]
Ticket mis en production
merge nécessaire @dferhod 
https://git.msh-lse.fr/larhra/ontome/-/merge_requests/89
