### ISSUE TITLE
Unable to activate proper property in a 7.1.3 profile

### ISSUE THREAD

**Issue by stephenhart8** [geovistory/ontome#200]
## Description of the bug
When activating the class E78_Curated_Holding in a CRM 7.1.3 profile, and selecting a property, both E78_Collection (from CRM 6.2) and E78_Curated_Holding are usable, but when specifying the range of the property, the scroll down menu disappears:
<img width="1211" alt="Capture d’écran 2024-11-06 à 11 04 20" src="https://github.com/user-attachments/assets/d78ded31-e7d2-4d87-8428-91cdb9f4115a">
<img width="1211" alt="Capture d’écran 2024-11-06 à 11 04 38" src="https://github.com/user-attachments/assets/5daaf35d-fb1d-4bec-a346-8907958378d2">

The profile does not have both versions of CIDOC CRM activated.
<img width="1211" alt="Capture d’écran 2024-11-06 à 11 05 38" src="https://github.com/user-attachments/assets/7328f180-f884-401a-b4a0-f0511232b374">

**Comment by perrauda** [comment]
Résolu

Dans la fonction _che.class_outgoing_inherited_properties_, en fin de requête on avait
`[...] che.class c JOIN che.class_version cv ON c.pk_class = cv.fk_class [...]` ce qui était insuffisant. J'ai rajouté en fin de ligne le filtre des namespaces: `AND cv.fk_namespace_for_version = ANY($2)`

Même chose avec _che.class_ingoing_inherited_properties_

La correction est effective directement en prod et également en dev.
