### ISSUE TITLE
Export fichier rdfs/owl/docx. Générer à l'avance et stocker le fichier sur le serveur

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#23]
- Problème d'export docx avec symogih
- Idée proposé par Djamel: génerer les fichiers des versions publiées à l'avance et n'avoir que les liens vers les fichiers directement
  - Attention aux multiples options

**Comment by joschne** [comment]
@perrauda can you describe, why this issue was created? What problem would it solve?

**Comment by perrauda** [comment]
> @perrauda can you describe, why this issue was created? What problem would it solve?

At one point, we thought that docx export was slow because of the many associations in a namespace.
Djamel came up with the idea of generating the file, albeit slowly, when a namespace was published. The file generated in this way could be downloaded immediately.
In the end, after inspection, it wasn't a data problem, but a bug in the code. Docx export is now fast again, so this ticket is not urgent, even if the idea is a good one.

**Comment by joschne** [comment]
> Docx export is now fast again, so this ticket is not urgent, even if the idea is a good one.

In that case I suggest to close the issue. Objections @perrauda, @valamercery, @dferhod ?

**Comment by perrauda** [comment]
> > Docx export is now fast again, so this ticket is not urgent, even if the idea is a good one.
> 
> In that case I suggest to close the issue. Objections @perrauda, @valamercery, @dferhod ?

No problem for me

**Comment by dferhod** [comment]
Ok for closing the issue.

**Comment by valamercery** [comment]
OK if you think this issue is no longer relevant.
