### ISSUE TITLE
Le terme "ongoing" est multiplié à la publication d'un profil

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#57]
**Describe the bug**
Lorsqu'on publie un nouveau profil, le label peut contenir un 'ongoing' en trop
![image](https://github.com/geovistory/ontome/assets/5019779/b416149d-0a68-479c-a246-c30cc90a0d34)

**To Reproduce**
1. Publish a profile whose label already contains "ongoing"

**Expected behavior**
N'avoir qu'un seul "ongoing" dans le label du nouveau profil ongoing.

**Comment by joschne** [comment]
@perrauda I don't fully understand this issue:

Why is "ongoing" doubled? Is it part of the Profile's label and then suffixed with "ongoing" automatically? 
If so, it would not be a real bug, but a new feature to eliminate the word "ongoing" from existing profile labels.

What is the envisaged solution for this issue?

**Comment by perrauda** [comment]
@joschne 
Because here it's a bad implementation for duplicating the profile label as the profile publication process has changed a little recently
````php
$newProfile->setStandardLabel($profile->getStandardLabel().' ongoing');
```
Here, the label already contains "ongoing".
The new implementation already ready (#39) will add "ongoing" in all cases, even if the user has modified the label to remove it.

**Comment by joschne** [comment]
Ok I understand. Thank you. To test I will have to publish a version of an ongoing profile?

**Comment by perrauda** [comment]
> Ok I understand. Thank you. To test I will have to publish a version of an ongoing profile?

To reproduce the bug, yes, with an _ongoing_ profile indeed.
An ongoing profile become a published profile, then a new ongoing is created.
This part is different from namespaces publications (ongoing stay ongoing, a new published version is created)

The fix isn't in preprod yet
