### ISSUE TITLE
Logo Geovistory manquant

### ISSUE THREAD

**Issue by perrauda** [geovistory/ontome#63]
**Describe the bug**
Le logo Geovistory a disparu

**Expected behavior**
Remettre le logo

**Comment by perrauda** [comment]
Après vérification: le logo n'a pas disparu, c'est juste que la branche où le problème apparaît ne contient pas encore le code du master

**Comment by joschne** [comment]
> Après vérification: le logo n'a pas disparu, c'est juste que la branche où le problème apparaît ne contient pas encore le code du master

@valamercery & @perrauda Can this issue be closed ?

**Comment by perrauda** [comment]
Indeed.
