### ISSUE TITLE
[Projets] Ajouter une langue par défaut du projet [1000]

### ISSUE THREAD

**Issue by valamercery** [geovistory/ontome#97]
[en cours de rédaction 23/09/2020]

FrancescoAujourd’hui à 16:26
et du coup c'est la langue préférée pour le porjet ET pour le NS root qu'il gère
pour les labels et textes du projet, de ses profils, de son NS, etc.
AlexandreAujourd’hui à 16:27
il y a 2 parties
FrancescoAujourd’hui à 16:27
car pas de contrôles
AlexandreAujourd’hui à 16:27
1/ au momment de la création du projet : enregistrer
FrancescoAujourd’hui à 16:27
juste un paramètre par défaut
AlexandreAujourd’hui à 16:27
2/ sur chaque select de la langue, il faut le mettre par défaut
FrancescoAujourd’hui à 16:27
oui
AlexandreAujourd’hui à 16:27
c'est tout
pour les projets déjà existants, on est bien d'accord c'est l'anglais par défaut ?
FrancescoAujourd’hui à 16:28
oui
et si on change, ça change lesnouvelles propriétés
ce qui est là rest dans sa langue
AlexandreAujourd’hui à 16:29
ca pourrait ouvrir à d'autres tickets
FrancescoAujourd’hui à 16:29
ça change juste le défaut
AlexandreAujourd’hui à 16:29
(mettre la ligne ayant cette langue en premier, dans un datatable, par exemple...)
FrancescoAujourd’hui à 16:29
pourquoi pas
DjamelAujourd’hui à 16:29
hmm
quelle est ta solution technique pour ça ?
FrancescoAujourd’hui à 16:30
l'essentiel est le défaut, pour l'ergonomie, sinon on doit de nouveau et de nouveau choisir
AlexandreAujourd’hui à 16:30
j'ai bien réussi pour le current namespace, mettre en 1er le projet activé
je sais plus comment :wink:
DjamelAujourd’hui à 16:30
une colonne cachée ?
ah si tu l'a déjà fait ok
AlexandreAujourd’hui à 16:30
oui

**Comment by joschne** [comment]
@valamercery and @perrauda 
How is this related to #76 and/or #77 ?

(Please close one issue in case of duplication.)

**Comment by valamercery** [comment]
This issue is a duplication of #76
